 #   all positions are relative to upper left corner of images
#   coordinates origin 0,0 = upper left corner
#   all position goes from 0 to 1
#   scale and kerning are multipliers
#   for string formatting check
#   http://www.python-course.eu/python3_formatted_output.php
# https://www.racedepartment.com/members/stormix43.412027/

[GENERAL]
background_image = background.png
# in pixels
size_x = 331
# in pixels
size_y = 320
# size factor
scale = 1.10
# separate multiple charset with comma eg. digi7black,digi7blue
# only insert charset that you really use
charsets = nfs15gear,nfs15speed,nfs15uom
# for valid lap checks
max_tyres_out = 2

[CHARS-NFS15GEAR]
# percent has to be escaped with %%
chars = 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ .%%/-+:
# in pixels
chars_size_x = 230
# in pixels
chars_size_y = 368

[CHARS-NFS15SPEED]
# percent has to be escaped with %%
chars = 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ .%%/-+:
# in pixels
chars_size_x = 230
# in pixels
chars_size_y = 368

[CHARS-NFS15UOM]
# percent has to be escaped with %%
chars = 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ .%%/-+:
# in pixels
chars_size_x = 224
# in pixels
chars_size_y = 60

[GEARS]
is_present = True
flash = True
background_flash = flash.png
# in seconds
flash_time = 0.1
# from 0 to 1
pos_x = 0.46
# from 0 to 1
pos_y = 0.57
# size factor
scale = 0.1125
charset = nfs15gear

[SPEEDOMETER]
is_present = True
uom = KPH
# from 0 to 1
pos_x = 0.35
# from 0 to 1
pos_y = 0.74
scale = 0.125
kerning = 1
charset = nfs15speed
format_string = {0:3.0f}
label_present = True
label = K
# from 0 to 1
label_pos_x = 0.42
# from 0 to 1
label_pos_y = 0.91
label_scale = 0.27
label_kerning = 1
label_charset = nfs15uom
uom_label_present = False
# from 0 to 1
uom_pos_x = 0.69
# from 0 to 1
uom_pos_y = 0.23
uom_scale = 1.5
uom_kerning = 1
uom_charset = nfsmw1

[REVMETER]
is_present = False
# from 0 to 1
pos_x = 0.63
# from 0 to 1
pos_y = 0.48
scale = 0.45
kerning = 1
charset = digi7black
format_string = {0:5.0f}
label_present = False
label = RPM
# from 0 to 1
label_pos_x = 0.82
# from 0 to 1
label_pos_y = 0.40
label_scale = 0.2
label_kerning = 1
label_charset = digi7black

[TYRES_TEMP]
is_present = False
pos_fl_x = 0.06
pos_fl_y = 0.66
pos_fr_x = 0.14
pos_fr_y = 0.66
pos_rl_x = 0.06
pos_rl_y = 0.72
pos_rr_x = 0.14
pos_rr_y = 0.72
scale = 0.18
kerning = 1
charset = digi7black
format_string = {0:3.0f}
label_present = False
label = TYR
label_pos_x = 0.14
label_pos_y = 0.56
label_scale = 0.18
label_kerning = 1
label_charset = digi7black
uom = C
uom_label_present = False
uom_pos_x = 0.22
uom_pos_y = 0.66
uom_scale = 0.18
uom_kerning = 1
uom_charset = digi7black

[TYRES_WEAR]
is_present = False
pos_fl_x = 0.06
pos_fl_y = 0.78
pos_fr_x = 0.14
pos_fr_y = 0.78
pos_rl_x = 0.06
pos_rl_y = 0.84
pos_rr_x = 0.14
pos_rr_y = 0.84
scale = 0.18
kerning = 1
charset = digi7black
format_string = {0:3.0f}
label_present = False
label = TYR
label_pos_x = 0.22
label_pos_y = 0.83
label_scale = 0.2
label_kerning = 1
label_charset = digi7black
uom = percent
uom_label_present = False
uom_pos_x = 0.22
uom_pos_y = 0.78
uom_scale = 0.18
uom_kerning = 1
uom_charset = digi7black

[LAPTIME]
is_present = False
pos_x = 0.75
pos_y = 0.72
scale = 0.18
kerning = 1.1
# dotkern is how much the chars like .: are closer to the next and previous
# 0 is no closer than other chars, 1 is no space from previous char
# default is 0.5 which is half as closer
dotkern = 0.5
charset = digi7black
format_string_mm = {0:2.0f}
format_string_ss = {0:02.0f}
format_string_ms = {0:03.0f}
# number of digits for the milliseconds
digits_ms = 3
label_present = False
label = CUR
label_pos_x = 0.65
label_pos_y = 0.72
label_scale = 0.18
label_kerning = 1
label_charset = digi7black

[LASTLAP]
is_present = False
pos_x = 0.75
pos_y = 0.78
scale = 0.18
kerning = 1.1
# dotkern is how much the chars like .: are closer to the next and previous
# 0 is no closer than other chars, 1 is no space from previous char
# default is 0.5 which is half as closer
dotkern = 0.5
charset = digi7black
format_string_mm = {0:2.0f}
format_string_ss = {0:02.0f}
format_string_ms = {0:03.0f}
# number of digits for the milliseconds
digits_ms = 3
label_present = False
label = LST
label_pos_x = 0.65
label_pos_y = 0.78
label_scale = 0.18
label_kerning = 1
label_charset = digi7black

[BESTLAP]
is_present = False
pos_x = 0.75
pos_y = 0.84
scale = 0.18
kerning = 1.1
# dotkern is how much the chars like .: are closer to the next and previous
# 0 is no closer than other chars, 1 is no space from previous char
# default is 0.5 which is half as closer
dotkern = 0.5
charset = digi7black
format_string_mm = {0:2.0f}
format_string_ss = {0:02.0f}
format_string_ms = {0:03.0f}
# number of digits for the milliseconds
digits_ms = 3
label_present = False
label = BST
label_pos_x = 0.65
label_pos_y = 0.84
label_scale = 0.18
label_kerning = 1
label_charset = digi7black
only_if_valid = False
max_tyres_out = 2

[FUELREM]
is_present = False
# LT liters GL gallons
uom = LT
format_string = {0:5.1f}
pos_x = 0.42
pos_y = 0.72
scale = 0.18
kerning = 1.1
charset = digi7black
label_present = False
label = FUEL
label_pos_x = 0.31
label_pos_y = 0.72
label_scale = 0.18
label_kerning = 1
label_charset = digi7black
uom_label_present = False
uom_pos_x = 0.54
uom_pos_y = 0.72
uom_scale = 0.18
uom_kerning = 1
uom_charset = digi7black

[FUELPERLAP]
is_present = False
# LT liters GL gallons
uom = LT
format_string = {0:5.1f}
pos_x = 0.42
pos_y = 0.78
scale = 0.18
kerning = 1.1
charset = digi7black
label_present = False
label = LT/L
label_pos_x = 0.31
label_pos_y = 0.78
label_scale = 0.18
label_kerning = 1
label_charset = digi7black
uom_label_present = False
uom_pos_x = 0.54
uom_pos_y = 0.78
uom_scale = 0.18
uom_kerning = 1
uom_charset = digi7black

[FUELREMLAPS]
is_present = False
uom = LP
format_string = {0:5.1f}
pos_x = 0.42
pos_y = 0.84
scale = 0.18
kerning = 1.1
charset = digi7black
label_present = False
label = REM
label_pos_x = 0.31
label_pos_y = 0.84
label_scale = 0.18
label_kerning = 1
label_charset = digi7black
uom_label_present = False
uom_pos_x = 0.54
uom_pos_y = 0.84
uom_scale = 0.18
uom_kerning = 1
uom_charset = digi7black

[DELTA]
is_present = False
uom = S
format_string = {0:+5.1f}
pos_x = 0.42
pos_y = 0.66
scale = 0.18
kerning = 1.1
# dotkern is how much the chars like .: are closer to the next and previous
# 0 is no closer than other chars, 1 is no space from previous char
# default is 0.5 which is half as closer
dotkern = 0.5
charset = digi7black
label_present = False
label = DT
label_pos_x = 0.31
label_pos_y = 0.66
label_scale = 0.18
label_kerning = 1
label_charset = digi7black
uom_label_present = False
uom_pos_x = 0.54
uom_pos_y = 0.66
uom_scale = 0.18
uom_kerning = 1
uom_charset = digi7black

[LAP]
is_present = False
format_string = {0:>7.0f}
pos_x = 0.75
pos_y = 0.66
scale = 0.18
kerning = 1.1
charset = digi7black
label_present = False
label = LAP
label_pos_x = 0.65
label_pos_y = 0.66
label_scale = 0.18
label_kerning = 1
label_charset = digi7black

[REVGRAPH]
is_present = True
# in pixels
size_x = 331
# in pixels
size_y = 320
frames = 360
# frame zero can be used as a background with static elements
always_show_frame_zero = False
prefix = rev_
pos_x = 0
pos_y = 0
scale_x = 1
scale_y = 1
label_present = False
label = RPM
label_pos_x = 0.2
label_pos_y = 0.4
label_scale = 0.3
label_kerning = 1
label_charset = digi7black
low_rev_perc = 0
high_rev_perc = 118

[FLASHZONE]
is_present = True
# limits are in percentage of max rev
limits = 0,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110
# last zone will flash?
last_zone_flash = True
# at which frequency?
last_zone_flash_freq = 0.1

[VALIDLAP]
is_present = False
image_valid   = valid.png
image_invalid = invalid.png

[FLAGS]
# 1 = blue
# 2 = Yellow
# 3 = black
# 4 = white
# 5 = checkered
# 6 = penalties pending
is_present = False
image1 = 1.png
image2 = 2.png
image3 = 3.png
image4 = 4.png
image5 = 5.png
image6 = 6.png



