# you can add as many windows as you wish
# set windows = number of windows
# for each window add a skin2, skin3, etc with the name
# eg skin2 = myskin
# keep in mind that more windows = more modules = more calculations = less fps
# currently windows works even when disabled from right assetto corsa bar
# https://www.racedepartment.com/members/stormix43.412027/

[GENERAL]
windows = 3
skin1 = default1
skin2 = NFS15SPD
skin3 = NFS15MAP